name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Create config files
      - name: Create config files
        run: |
          # Create firebase config
          cat > firebase-config.js << 'EOL'
          ${{ secrets.FIREBASE_CONFIG }}
          EOL
          
          # Create app config
          cat > config.js << 'EOL'
          ${{ secrets.APP_CONFIG }}
          EOL
          
          # Verify files
          echo "Created files:"
          ls -la *.js
          
      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./


