name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Create config files
      - name: Create firebase config
        run: |
          cat > firebase-config.js << 'EOF'
          // Initialize Firebase with your config
          const firebaseConfig = {
              apiKey: "${{ secrets.FIREBASE_API_KEY }}",
              authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
              databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}",
              projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
              storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
              messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
              appId: "${{ secrets.FIREBASE_APP_ID }}"
          };
          firebase.initializeApp(firebaseConfig);
          const database = firebase.database();
          export { database };
          EOF
          
          # Verify file was created
          echo "Firebase config created:"
          ls -l firebase-config.js

      - name: Create app config
        run: |
          cat > config.js << 'EOF'
          export const config = {
              scriptURL: "${{ secrets.SCRIPT_URL }}",
              githubPages: {
                  baseUrl: "https://sadjei78.github.io/agl-auc25",
                  environment: "production"
              }
          };
          EOF

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./



