name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Create a deployment directory
      - name: Create deployment directory
        run: |
          mkdir deploy
          cp -r * deploy/ || true
          cd deploy
          # Remove template file if it exists
          rm -f firebase-config.template.js
      
      # Create config files in deployment directory
      - name: Create firebase config
        run: |
          cd deploy
          cat > firebase-config.js << 'EOL'
          // Import the functions you need from the SDKs you need
          import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';
          import { getAuth, signInWithEmailAndPassword, createUserWithEmailAndPassword } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
          import { getDatabase, ref, set, onValue, push, get, child } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';

          // Your web app's Firebase configuration
          const firebaseConfig = {
            apiKey: "${FIREBASE_API_KEY}",
            authDomain: "${FIREBASE_AUTH_DOMAIN}",
            databaseURL: "${FIREBASE_DATABASE_URL}",
            projectId: "${FIREBASE_PROJECT_ID}",
            storageBucket: "${FIREBASE_STORAGE_BUCKET}",
            messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID}",
            appId: "${FIREBASE_APP_ID}"
          };

          // Initialize Firebase
          const app = initializeApp(firebaseConfig);
          const auth = getAuth(app);
          const database = getDatabase(app);

          // Export the initialized instances and all needed functions
          export { app, auth, database, ref, set, onValue, push, get, child };
          EOL

          # Replace environment variables
          sed -i "s|\${FIREBASE_API_KEY}|${{ secrets.FIREBASE_API_KEY }}|g" firebase-config.js
          sed -i "s|\${FIREBASE_AUTH_DOMAIN}|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" firebase-config.js
          sed -i "s|\${FIREBASE_DATABASE_URL}|${{ secrets.FIREBASE_DATABASE_URL }}|g" firebase-config.js
          sed -i "s|\${FIREBASE_PROJECT_ID}|${{ secrets.FIREBASE_PROJECT_ID }}|g" firebase-config.js
          sed -i "s|\${FIREBASE_STORAGE_BUCKET}|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" firebase-config.js
          sed -i "s|\${FIREBASE_MESSAGING_SENDER_ID}|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" firebase-config.js
          sed -i "s|\${FIREBASE_APP_ID}|${{ secrets.FIREBASE_APP_ID }}|g" firebase-config.js

      # Verify firebase config contents
      - name: Check firebase config
        run: |
          cd deploy
          echo "Contents of firebase-config.js:"
          cat firebase-config.js

      - name: Create app config
        run: |
          cd deploy
          echo "export const config = {
            scriptURL: \"${{ secrets.SCRIPT_URL }}\",
            githubPages: {
              baseUrl: \"https://sadjei78.github.io/agl-auc25/auction.html\",
              environment: \"production\"
            }
          };" > config.js

      # Create Firebase rules file
      - name: Create Firebase rules
        run: |
          cd deploy
          echo '{
            "rules": {
              "users": {
                "$uid": {
                  ".read": "$uid === auth.uid || root.child('\''admins'\'').child(auth.uid).exists()",
                  ".write": "$uid === auth.uid || root.child('\''admins'\'').child(auth.uid).exists()"
                }
              },
              "chat": {
                ".read": "auth != null",
                ".write": "auth != null"
              },
              "activeUsers": {
                ".read": true,
                ".write": true,
                "$user_id": {
                  ".read": true,
                  ".write": true,
                  "email": {
                    ".validate": "newData.isString()"
                  },
                  "lastActive": {
                    ".validate": "newData.isNumber()"
                  }
                }
              },
              "messages": {
                ".read": "auth != null",
                ".write": "auth != null",
                "$user_id": {
                  ".read": "auth != null",
                  ".write": "auth != null"
                }
              },
              "items": {
                ".read": true,
                ".write": "auth != null && root.child('\''admins'\'').child(auth.uid).exists()"
              },
              "admins": {
                ".read": "auth != null",
                ".write": false
              },
              "typing": {
                ".read": true,
                ".write": "auth != null"
              }
            }
          }' > firebase-rules.json

      - name: List deployment files
        run: |
          cd deploy
          echo "Files to be deployed:"
          ls -la

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          exclude_assets: ''
          keep_files: false
          commit_message: "Deploy with updated Firebase configuration"

env:
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}



